import = ["/home/rragni/.config/alacritty/catppuccin-mocha.toml"]

[colors.primary]
background = "#1A1D23"

[font]
size = 16

[font.bold]
family = "DejaVuSansMono"
style = "Regular"

[font.bold_italic]
family = "DejaVuSansMono"
style = "Regular"

[font.italic]
family = "DejaVuSansMono"
style = "Regular"

[font.normal]
family = "DejaVuSansMono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[shell]
program = "/bin/bash"

[window]
startup_mode = "Fullscreen"
